# Generated by Django 3.2.8 on 2022-04-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo',
        ),
    ]
